### ISSUE TITLE
Exit Status 1 on Startup

### ISSUE THREAD

**Issue by darrindickey** [itsabot/abot#175] opened 2016-09-02 01:36 UTC
I've run into problems pretty much every step of the way (not just with the app), but I've overcome most of them. I've finally gotten to where I can run "abot server" and it appears to start. But all I get in the terminal and on the browser page is "{"Msg":"exit status 1"}".

Here is the terminal output when I do "abot server":
2016/09/01 20:25:40 training classifiers
2016/09/01 20:25:40 started abot
2016/09/01 20:25:40 updating analytics
2016/09/01 20:25:41 failed to retrieve version number. json: cannot unmarshal number into Go value of type core.PluginJSON
2016/09/01 20:25:54 internal error. exit status 1
2016/09/01 20:25:54 internal error. exit status 1
2016/09/01 20:25:57 internal error. exit status 1

Is there some kind of log that might show what the issue is? I don't really see anything in the Console that helps.

**Comment by egtann** [comment] 2016-09-02 16:19
grep for "failed to retrieve version number" to find the trouble line.
Closing (duplicate of #171)

**Closed** 2016-09-02 16:19 UTC

**Comment by darrindickey** [comment] 2016-09-02 16:53
I think I did that already. The only place I found that URL was in src/github.com/itsabot/abot/core/analytics.go. I changed the URL there to https://raw.githubusercontent.com/itsabot/abot/master/plugins.json, but I continue to get this error.

**Comment by egtann** [comment] 2016-09-02 18:27
Well, it's not an important bit of code. I'd recommend commenting it out for now.
