### ISSUE TITLE
Error on 'abot server' command

### ISSUE THREAD

**Issue by chajas** [itsabot/abot#62] opened 2016-04-12 09:02 UTC
When i execute the abot server command i get an error as

/home/xxx/go/src/github.com/itsabot/plugin_hello/plugin.json: no such file or directory

my plugins.json looks like this:

```
{
        "Name": "Abot",
        "Description": "Digital assistant framework",
        "Version": "0.2.0-alpha",
        "ImportPath": "github.com/itsabot/abot",
        "Dependencies": {
                "github.com/itsabot/plugin_onboard": "*"
        }
}
```
 
Can you suggest why I get this error. This was working fine sometime back though.
I am working on Ubuntu Virtual Box. 

Thanks,

**Comment by njaremko** [comment] 2016-04-12 14:07
Are you looking at the correct plugins.json? It's looking in `$GOPATH/src/github.com/itsabot/abot`

Do you have a folder `/home/xxx/go/src/github.com/itsabot/plugin_hello/`?

**Comment by egtann** [comment] 2016-04-12 15:35
You don't have plugin_hello in your plugins.json. I suspect that you need to re-run `abot p install`

**Comment by chajas** [comment] 2016-04-13 11:01
Hi,
I don't have the plugin_hello folder in my path only the plugin_onboard directory but nor do I have it in my plugin.json. 
Also running the command `abot p install` gives the same error.

**Comment by egtann** [comment] 2016-04-14 01:00
@chajas I'm afraid I'm not able to reproduce the problem with the information given. Looking through the `installPlugins` function (which runs on `abot p install`), I can't see anything that would attempt to open a plugin.json file causing an error like this.

I would try clean installing everything.

**Comment by egtann** [comment] 2016-04-19 17:27
Closing this issue, since I can't reproduce it.

**Closed by egtann** 2016-04-19 17:27 UTC
