### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by raisudeen** [itsabot/abot#156] opened 2016-07-14 11:03 UTC
Hi,

First of all, thanks a lot for this awesome framework.
I tried to install a plugin. But, Im facing below errors for all plugins.

> $ abot plugin install
> Fetching 1 plugin...
> Installing plugins...
> could not install plugins. failed to update itsabot.org.
> Put https://www.itsabot.org/api/plugins.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Can you please let me know how to rectify this?
Thanks in advance.
-Raisudeen.

**Comment by egtann** [comment] 2016-07-14 15:43
That's a timeout, most likely caused by a slow or unavailable internet connection. Does this keep happening for you?  What's your network speed?

**Comment by egtann** [comment] 2016-07-16 05:10
Closing while waiting for a reply

**Closed by egtann** 2016-07-16 05:10 UTC

**Comment by raisudeen** [comment] 2016-07-18 06:43
Sorry for my delayed reply. I tried it in both 12Mbps and 24Mbps network. This occurs often now. What is the timeout configuration for this? Is it possible to increase it more?

**Comment by egtann** [comment] 2016-07-18 14:14
You can increase it from 10 seconds to more. grep for "Timeout" in the code and increase them from 10*time.Second to time.Minute.
