### ISSUE TITLE
running abot migrationsPassword

### ISSUE THREAD

**Issue by Jambo-Dunia** [itsabot/abot#23] opened 2016-04-01 17:53 UTC
I'm fairly new to GO and Postgresql but I am excited to work with this. I'm having a slight problem installing however:

`[ok] checking for go binary` 
`[ok] checking GOPATH` 
`[ok] installing dependency manager`
`[ok] syncing dependencies`
`[ok] installing glock hook`
`[ok] installing abot`
`[ok] checking for postgres`
`[ok] checking for psql binary`
`[?] checking for postgres userPassword for user postgres: `
`[ok] checking for postgres user`
`[?] checking for abot databasePassword for user postgres:`
`[ok] checking for abot database`
`[?] checking for abot_test databasePassword for user postgres:`
`[ok] checking for abot_test database`
`[?] running abot migrationsPassword for user postgres:`
`Password for user postgres: `
`Password for user postgres:`
`Password for user postgres:`

     
it continues to print `Password for user postgres:` even after I input the password. It will continue to do so until it reaches the end and prints: `psql: fe_sendauth: no password supplied` warnings and fails.

This could be a small problem I'm overlooking, sorry in advance.

**Comment by egtann** [comment] 2016-04-01 18:18
Marking this as a duplicate of #22. Let's debug it in there.

**Closed by egtann** 2016-04-01 18:18 UTC
