### ISSUE TITLE
Plugin Install issue around github.com/itsabot/abot/shared/pkg

### ISSUE THREAD

**Issue by bwcall** [itsabot/abot#33] opened 2016-04-02 11:51 UTC
Hi ,

I am getting some cannot find package "github.com/itsabot/abot/shared/pkg" errors on abot plugin install , I can see from looking a bit in the code that the stripe plugin is using this I guess deleted package in their go file , it must be depended on elsewhere in other plugins also. I have not found where it has been renamed to or moved to for updating the plugin files though. 

Can someone advise?

Thanks
Barry

**Comment by bwcall** [comment] 2016-04-02 13:06
Also I notice that since I filled my plugins.json up with 5/6 plugins , now they are re-downloaded everytime it seems even when i reduce them back down to the bare minimum onboard plugin , is there a context being stored to the db and the json is being ignored , its quite strange.

Even though stripe was the only plugin using this pkg package it still remembers that it has ever been referenced after the json changes.

**Comment by egtann** [comment] 2016-04-02 15:15
That's an old plugin using an outdated API. Sorry bout that. Part of this v0.2 release (ETA June 1, 2016) is to get many of these plugins into working form. Right now the only one expected to work is weather (but pull requests on any of them would be welcome!).

Are you running `abot plugin install` each time after changing plugins.json? That should delete plugins.go and recreate it, preventing you from downloading the plugins again.  If not, let me know as that would be a bug. In that case, delete plugins.go manually and re-run `abot plugin install` after that as a temporary fix.

**Comment by bwcall** [comment] 2016-04-03 00:59
Hi ,

Yes I figured it was just outdated thats fine , the plugin install is a bit strange though even deleting the plugins.go and re-running the install seems to still bring in the original full set of plugins that I referenced originally.

You should be able to reproduce if you run install with plugins.json with extra entries and then delete the lines except for onboard/weather and delete the unlying the directories for stripe / sendgrid etc. so there is no references ( I know that isn't the ideal approach!)

Another way is to do as above and not do the delete of directories referring to the plugins that you no longer reference in the plugins.json , seems to still try to build them even after reference is removed in json.

**Comment by egtann** [comment] 2016-04-03 16:57
I'm not able to replicate the issue. I add a plugin to plugins.json, run `abot p install`, and it downloads it to my `$GOPATH`. I delete that line from my plugins.json, delete the plugin directory from my `$GOPATH`, and re-run `abot p install`, but the plugin isn't downloaded again.

**Comment by egtann** [comment] 2016-04-04 16:38
I'm closing this issue for now, since I can't reproduce it. @bwcall if you still experience problems with plugin installs, we can discuss them here, but for now, it appears everything is working as expected on Linux and OSX.

**Closed by egtann** 2016-04-04 16:38 UTC
